### ISSUE TITLE
Seekers Instantly Spawn with Hiders

### ISSUE THREAD

**Issue by Tyguy20** [Steffion/BlockHunt#344] opened 2015-08-09 12:23 UTC
I have a Seeker spawn setup, in a locked cage, though, the Seekers just skip that and spawn right at the Hiders and start to search but no blocks had time to run, so they all die. Then after the 20 seconds they are spawned in at the Hiders again, so the game still thinks they haven't been spawned yet. I have no clue whats happening or how to fix it. Please help.

**Comment by vanwiththeplan** [comment] 2016-01-25 00:41
i am having the same problem

**Comment by Steffion** [comment] 2016-01-25 09:42
Duplicate of #356 . Check my comment there.

**Closed by Steffion** 2016-01-25 09:42 UTC
